---
# This playbook deploys the whole application stack in this site.  

- name: Setup Jenkins master
  hosts: all
  remote_user: root
  serial: 5

- debug: var=hostvars[inventory_hostname] verbosity=1

#  roles:
#    - java
#    - jenkins
